import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Crear productos de cosmética ficticios pero realistas
  const products = [
    {
      sku: 'SER001',
      name: 'Serum Antioxidante Vitamina C',
      brand: 'GlowBeauty',
      category: 'Serum',
      supplier: 'CosmeticaPlus',
      stock: 45,
      stock_in_transit: null,
      sales_last_7: 8,
      sales_last_30: 32,
      last_restock_date: new Date('2024-12-01'),
      cost_price: 25.00,
      sale_price: 50.00,
      margin: 25.00,
      threshold: 10,
      is_strategic: true,
    },
    {
      sku: 'CRM001',
      name: 'Crema Hidratante Facial Día',
      brand: 'NaturaSkin',
      category: 'Crema',
      supplier: 'BellezaDistribuciones',
      stock: 60,
      stock_in_transit: 20,
      sales_last_7: 12,
      sales_last_30: 45,
      last_restock_date: new Date('2024-11-20'),
      cost_price: 15.00,
      sale_price: 35.00,
      margin: 20.00,
      threshold: 15,
      is_strategic: false,
    },
    {
      sku: 'MAQ001',
      name: 'Base Líquida Matificante',
      brand: 'MakeUpPro',
      category: 'Maquillaje',
      supplier: 'CosmeticaPlus',
      stock: 25,
      stock_in_transit: null,
      sales_last_7: 6,
      sales_last_30: 18,
      last_restock_date: new Date('2024-11-15'),
      cost_price: 20.00,
      sale_price: 45.00,
      margin: 25.00,
      threshold: 8,
      is_strategic: false,
    },
    {
      sku: 'SER002',
      name: 'Serum Retinol Antiarrugas',
      brand: 'AgeDefy',
      category: 'Serum',
      supplier: 'BellezaDistribuciones',
      stock: 30,
      stock_in_transit: null,
      sales_last_7: 4,
      sales_last_30: 15,
      last_restock_date: new Date('2024-11-25'),
      cost_price: 35.00,
      sale_price: 75.00,
      margin: 40.00,
      threshold: 5,
      is_strategic: true,
    },
    {
      sku: 'CRM002',
      name: 'Crema Contorno de Ojos',
      brand: 'GlowBeauty',
      category: 'Crema',
      supplier: 'CosmeticaPlus',
      stock: 40,
      stock_in_transit: 10,
      sales_last_7: 9,
      sales_last_30: 28,
      last_restock_date: new Date('2024-12-05'),
      cost_price: 18.00,
      sale_price: 40.00,
      margin: 22.00,
      threshold: 10,
      is_strategic: false,
    },
    {
      sku: 'MAQ002',
      name: 'Labial Mate Rojo',
      brand: 'LipLux',
      category: 'Maquillaje',
      supplier: 'BellezaDistribuciones',
      stock: 55,
      stock_in_transit: null,
      sales_last_7: 15,
      sales_last_30: 50,
      last_restock_date: new Date('2024-11-30'),
      cost_price: 8.00,
      sale_price: 20.00,
      margin: 12.00,
      threshold: 12,
      is_strategic: true,
    },
    {
      sku: 'SER003',
      name: 'Serum Hialurónico Puro',
      brand: 'HydraGlow',
      category: 'Serum',
      supplier: 'CosmeticaPlus',
      stock: 35,
      stock_in_transit: 15,
      sales_last_7: 7,
      sales_last_30: 22,
      last_restock_date: new Date('2024-11-28'),
      cost_price: 28.00,
      sale_price: 55.00,
      margin: 27.00,
      threshold: 8,
      is_strategic: false,
    },
    {
      sku: 'CRM003',
      name: 'Crema Solar SPF 50',
      brand: 'SunProtect',
      category: 'Crema',
      supplier: 'BellezaDistribuciones',
      stock: 70,
      stock_in_transit: null,
      sales_last_7: 18,
      sales_last_30: 60,
      last_restock_date: new Date('2024-12-02'),
      cost_price: 12.00,
      sale_price: 28.00,
      margin: 16.00,
      threshold: 20,
      is_strategic: false,
    },
    {
      sku: 'MAQ003',
      name: 'Paleta de Sombras Neutras',
      brand: 'EyeShadow',
      category: 'Maquillaje',
      supplier: 'CosmeticaPlus',
      stock: 20,
      stock_in_transit: 5,
      sales_last_7: 3,
      sales_last_30: 10,
      last_restock_date: new Date('2024-11-18'),
      cost_price: 30.00,
      sale_price: 65.00,
      margin: 35.00,
      threshold: 5,
      is_strategic: false,
    },
    {
      sku: 'SER004',
      name: 'Serum Niacinamida Poro Reductor',
      brand: 'PoreFix',
      category: 'Serum',
      supplier: 'BellezaDistribuciones',
      stock: 28,
      stock_in_transit: null,
      sales_last_7: 5,
      sales_last_30: 17,
      last_restock_date: new Date('2024-11-22'),
      cost_price: 22.00,
      sale_price: 48.00,
      margin: 26.00,
      threshold: 6,
      is_strategic: true,
    },
    {
      sku: 'CRM004',
      name: 'Crema Corporal Hidratante',
      brand: 'BodyGlow',
      category: 'Crema',
      supplier: 'CosmeticaPlus',
      stock: 80,
      stock_in_transit: 25,
      sales_last_7: 20,
      sales_last_30: 75,
      last_restock_date: new Date('2024-12-03'),
      cost_price: 10.00,
      sale_price: 25.00,
      margin: 15.00,
      threshold: 25,
      is_strategic: false,
    },
    {
      sku: 'MAQ004',
      name: 'Máscara de Pestañas Volumen',
      brand: 'LashBoost',
      category: 'Maquillaje',
      supplier: 'BellezaDistribuciones',
      stock: 50,
      stock_in_transit: null,
      sales_last_7: 11,
      sales_last_30: 38,
      last_restock_date: new Date('2024-11-26'),
      cost_price: 14.00,
      sale_price: 32.00,
      margin: 18.00,
      threshold: 15,
      is_strategic: true,
    },
    {
      sku: 'SER005',
      name: 'Serum Peptidos Antiedad',
      brand: 'YouthRenew',
      category: 'Serum',
      supplier: 'CosmeticaPlus',
      stock: 22,
      stock_in_transit: 8,
      sales_last_7: 2,
      sales_last_30: 8,
      last_restock_date: new Date('2024-11-10'),
      cost_price: 40.00,
      sale_price: 85.00,
      margin: 45.00,
      threshold: 4,
      is_strategic: true,
    },
    {
      sku: 'CRM005',
      name: 'Crema Manos Nutritiva',
      brand: 'HandCare',
      category: 'Crema',
      supplier: 'BellezaDistribuciones',
      stock: 65,
      stock_in_transit: null,
      sales_last_7: 14,
      sales_last_30: 52,
      last_restock_date: new Date('2024-12-04'),
      cost_price: 9.00,
      sale_price: 22.00,
      margin: 13.00,
      threshold: 18,
      is_strategic: false,
    },
    {
      sku: 'MAQ005',
      name: 'Rubor Polvo Natural',
      brand: 'BlushGlow',
      category: 'Maquillaje',
      supplier: 'CosmeticaPlus',
      stock: 38,
      stock_in_transit: 12,
      sales_last_7: 8,
      sales_last_30: 26,
      last_restock_date: new Date('2024-11-29'),
      cost_price: 16.00,
      sale_price: 38.00,
      margin: 22.00,
      threshold: 10,
      is_strategic: false,
    },
  ];

  for (const product of products) {
    await prisma.product.create({
      data: product,
    });
  }

  console.log('Seeded 15 products successfully');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
